name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        echo "Docker Hub - Login..."
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - name: Build Docker Image
      run: |
        docker build -t dngdev/docker-graphql-automation:0.0.1 .
        docker build -t dngdev/docker-graphql-automation:latest .
    - name: Push Docker Image
      run: |
        docker push dngdev/docker-graphql-automation:0.0.1
        docker push dngdev/docker-graphql-automation:latest
        
      
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
