name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        echo "Docker Hub Login..."
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        echo "End of Login..."
        
      
    # - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
